version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine
  
  discountdb:
    image: postgres
  
  pgadmin:
     image: dpage/pgadmin4

  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: /Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: /Basket.API/Dockerfile
      
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order.API/Dockerfile


  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile


  discount.grpc:
    container_name: discount.grpc
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile

  ecomwebapp:
    image: ${DOCKER_REGISTRY-}ecomwebapp
    build:
      context: .
      dockerfile: WebApps/EcomWebApp/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:






